version: '3.1'

services:

  wordpress:
    networks:
      - proxy
      - default
    image: docker.io/library/wordpress:latest
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_CONFIG_EXTRA: |
                        define('WP_HOME', 'http://blog-a.app.sagdas.net');
                        define('WP_SITEURL', 'http://blog-a.app.sagdas.net');
    volumes:
      - wordpress:/var/www/html

  db:
    image: docker.io/library/mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:

networks:
  default:
  proxy:
    external:
      name: proxy